---
title: "Sentiment Analysis of 2017 New York Times Comments "
format: html
---

# Introduction

# Data Inspection

```{r}

library(dplyr)
library(ggplot2)
library(plotly)

library(tidyr)
library(tidytext)
library(SnowballC)

library(textmineR)
library(textstem)
library(tm)
library(syuzhet)

library(tibble)

library(textclean)
library(furrr)


```


```{r}


nyt_comments17 |> 
    glimpse()


```


```{r}


nyt_comments17<-read.csv("nyt_comments17.csv")


```


```{r}


nyt_comments17 |> head()


```

```{r}

saveRDS(nyt_comments17, "nyt_comments17.rds")


```

```{r}


nyt_comments17_short<-nyt_comments17 |> 
    select(-commentType)



```

We will remove the column commentType


```{r}

nyt_comments17_short |> 
    glimpse()



```

```{r}


saveRDS(nyt_comments17_short, "nyt_comments17_short.rds")


```

# Data Preparation


We will need a function to clean the text in the New York Times commentBody.  




```{r}

clean_comment_text <- function(text) {
  text %>%
    gsub("<.*?>", " ", .) %>%                  # Remove HTML/Markdown tags like <br/>
    gsub("\\\\", " ", .) %>%                   # Remove backslashes
    gsub("[^\\p{L}\\p{N}\\s!?\\p{Emoji_Presentation}]", " ", ., perl = TRUE) %>%  
    gsub("\\s+", " ", .) %>%                   # Replace multiple spaces with single space
    trimws()
}



```

```{r}


nyt_comments_clean<-nyt_comments17_short |> 
    mutate(clean_comments = clean_comment_text(commentBody))


```



```{r}


nyt_comments_clean |> 
    glimpse()



```

```{r}

saveRDS(nyt_comments_clean, "nyt_comments_clean.rds")


```


# Sentiment extraction
